networks:
  onlix:
    external: true

services:
  user-service:
    build: .
    image: user-service:dev
    container_name: onlix-user-service
    env_file:
      - ./dev.env
    ports:
      - "8081:8080"
    networks: 
      - onlix    