spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 60000 # ms

jwt:
  access-token-expire-time: 3600000    # 1시간
  refresh-token-expire-time: 604800000 # 7일

cors:
  allowed-origins: "http://localhost:3000"
#logging:
#  level:
#    root: INFO
#    org:
#      springframework: INFO
#      mybatis: INFO
#      hibernate: ERROR
#    com:
#      labg:
#        sfa: INFO
#      zaxxer:
#        hikari: OFF
#    javax:
#      sql:
#        DataSource: OFF
#    jdbc:
#      audit: OFF
#      resultset: OFF
#      resultsettable: OFF
#      sqlonly: INFO
#      sqltiming: OFF
#      connection: OFF