spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 60000 # ms

#logging:
#  level:
#    root: INFO
#    org:
#      springframework: INFO
#      mybatis: INFO
#      hibernate: ERROR
#    com:
#      labg:
#        sfa: INFO
#      zaxxer:
#        hikari: OFF
#    javax:
#      sql:
#        DataSource: OFF
#    jdbc:
#      audit: OFF
#      resultset: OFF
#      resultsettable: OFF
#      sqlonly: INFO
#      sqltiming: OFF
#      connection: OFF